language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

install:
  - sudo apt-get update -y
  - sudo apt-get install graphicsmagick libjpeg-dev
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install "coveralls==1.1" coverage
  - coverage report
  - coveralls
