language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - sudo apt-get update -y
  - sudo apt-get install graphicsmagick libjpeg-dev
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install coverage
  - coverage report
